version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11
      - name: localstack
        image: localstack/localstack:0.8.7
        environment:
          ENV_INTERNAL_TEST_RUN: true
          DEBUG: 1
          SERVICES: 's3,elasticsearch'
    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Install
          command: yarn
      - run:
          name: Bootstrap
          command: yarn bootstrap 
      - run:
          name: Lint
          command: yarn eslint
      - run:
          name: Build 
          command: yarn build 
      - run:
          name: Test
          environment:
            LOCALSTACK_HOST: localstack
          command: yarn test
    
      - run:
          name: Build Documentation
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              yarn docs-build
            fi
      
      - run:
          name: Deploy example to aws
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              cd example
              yarn
              ./node_modules/.bin/kes cf deploy --template node_modules/@sat-utils/api/template --deployment dev --region us-east-1 --role arn:aws:iam::552819999234:role/sat-api-deployer-role-DeployerRole-JBBKUABAELDR
            fi

